name: Go Environment
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Print
    # 此作业在 Linux 上运行
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: go version
